version: "3"
services:
  snisni-frontend:
    volumes:
    - ../frontend:/usr/src/app
    working_dir: /usr/src/app
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: snisni-frontend
    command: "npm run dev"
    ports: 
      - "80:3000"
    env_file:
      ../frontend/docker.env
    networks:
      - code-network


networks:
  code-network:
    driver: bridge
