version: "3"
services:
  frontend:
    container_name: snisni-frontend
    volumes:
      - ../frontend:/usr/src/frontend
    working_dir: /usr/src/frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: "npm run dev"
    ports: 
      - "80:3000"
    env_file:
      ../frontend/docker.env
    networks:
      - code-network
    depends_on: 
      - api
  api:
    container_name: snisni-api
    volumes:
      - ../api:/var/www:cached
      - ./web/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - ~/.ssh:/root/.ssh/
    build: 
      context: ../api
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    networks: 
      - code-network



networks:
  code-network:
    driver: bridge
