version: "3"
services:
  frontend:
    container_name: snisni-frontend
    volumes:
      - ../frontend:/usr/src/frontend
      - ../frontend/node_modules:/usr/src/frontend/node_modules
    build:
      context: ../frontend
      dockerfile: Dockerfile
    command: "npm run dev"
    ports:
      - "80:3000"
    env_file: ../frontend/dev.env
    networks:
      - backend
    depends_on:
      - webserver
  api:
    container_name: snisni-api
    volumes:
      - ../api:/var/www:cached
      - ../api/vendor:/var/www/vendor
      - ./web/www.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - ~/.ssh:/root/.ssh/
    build:
      context: ../api
      dockerfile: Dockerfile
    restart: always
    expose:
      - "9000"
    networks:
      - backend
    depends_on:
      - database
  webserver:
    container_name: snisni-server
    restart: always
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ../api:/var/www
      - ./web/sites:/etc/nginx/conf.d
    working_dir: /var/www
    ports:
      - "8080:80"
      - "4430:443"
    depends_on:
      - api
    networks:
      - backend
  database:
    container_name: snisni-database
    build: 
      context: ./database
      dockerfile: Dockerfile
    env_file: ./database/.env
    ports: 
      - "5432:5432"
    networks: 
      - backend
networks:
  backend:
    driver: bridge
